- hosts: localhost
  connection: localhost
  gather_facts: false

  vars:
    local_pc_public_ip: 77.126.63.26
    ansible_internal_ip: 15.188.172.129
    key_name: my_aws
    sg_group_name: challenge-sg
    ec2_default_user: "ubuntu"
    ec2_region: eu-west-3
    ec2_instance_ami: ami-0bb607148d8cf36fb 
    ec2_instance_type: t2.micro
    ec2_instance_count: 1

  roles:
    - provision
  

- hosts: my_ec2
  name: Deploy webserver
  become: yes
  gather_facts: true

  roles:
    - deploy_web_app