---
local_pc_public_ip: 
ansible_internal_ip: 
key_name: my_aws
sg_group_name: challenge-sg
ec2_default_user: "ubuntu"
ec2_region: eu-west-3
ec2_instance_ami: ami-0bb607148d8cf36fb 
ec2_instance_type: t2.micro
ec2_instance_count: 1
ec2_instance_env:
  BOTO_USE_ENDPOINT_HEURISTICS: True